apiVersion: v1
kind: ConfigMap
metadata:
  name: aerolink-config
  namespace: aerolink
data:
  # Environment Variables shared across services
  NODE_ENV: "production"
  AWS_REGION: "us-east-1"
  DYNAMODB_TABLE_NAME: "aerolink-baggage"
  EVENT_BUS_NAME: "aerolink-saga-bus"
  REDIS_URL: "redis://aerolink-redis.n5hbdw.0001.use1.cache.amazonaws.com:6379"
  DATABASE_URL: "postgresql://postgres:%21ISdV9h.IViU%3CzOl%5D_myvIqv%5D1Sd@aerolink-aurora.cluster-cyv4e2ee83we.us-east-1.rds.amazonaws.com:5432/postgres?schema=public"
  
  # API URLs (Internal Routing inside EKS via Kubernetes DNS)
  NEXT_PUBLIC_API_URL: "http://api.aerolink.internal"
  NEXT_PUBLIC_FLIGHT_API_URL: "http://flight-service.aerolink.svc.cluster.local:80"
  NEXT_PUBLIC_AUTH_API_URL: "http://auth-service.aerolink.svc.cluster.local:80"
  NEXT_PUBLIC_BOOKING_API_URL: "http://booking-service.aerolink.svc.cluster.local:80"
  NEXT_PUBLIC_BAGGAGE_API_URL: "http://baggage-service.aerolink.svc.cluster.local:80"
