apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: baggage-service-scaler
  namespace: aerolink
spec:
  scaleTargetRef:
    name: baggage-service
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "70"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: flight-service-scaler
  namespace: aerolink
spec:
  scaleTargetRef:
    name: flight-service
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "70"
